### PR TITLE
Add ABFRL Breach Logo

### PR DESCRIPTION
**Pull request by maxxcrawford**
Preview: 

ABFRL

Note — I also optimized a few other breach logos. (See Files changed for a nice comparison)

### CODE REVIEW

**Review by pdehaan — APPROVED** [review]
LGTM. Thanks!

**Comment by pdehaan** [comment]
Re: public/img/logos/Zoosk.png, did you want to resize that down to 150x150 while we're at it? I think it's still 200x200 after the optimization.

**Comment by pdehaan** [comment]
And i think the gamerzplanet(?) one is W: 161px | H: 161px

**Comment by tmorganPDC** [comment]
@maxxcrawford [1]()

**Comment by tmorganPDC** [comment]
(Axis). @tmorganPDC

**Comment by tmorganPDC** [comment]
Ted: MLK

**Comment by tmorganPDC** [comment]
> Preview: 
> 
> 
> 
> ABFRL
> 
> 
> 
> Note — I also optimized a few other breach logos. (See Files changed for a nice comparison)

**Comment by pdehaan** [comment]
Oh interesting.
I don't see these deployed to https://monitor.firefox.com/breach-details/ABFRL.
I wonder if it's because this was merged into main-kanary and not main.
Because I _do_ see the newer logos merged an hour ago on https://monitor.firefox.com/breaches.

**Pull request merged**
