### PR TITLE
Bump a few outdated dependencies to fix npm audit script

### PR DESCRIPTION
**Pull request by pdehaan**
I think the high priority, failure causing dependency was "nodemon", and the postcss/stylelint were all "low priority" errors.

### CODE REVIEW

**Comment by jrbenny35** [comment]
Hey Peter. I am not sure what is happening. It seems to be failing a consistently. Can you try removing the ```nodemon``` change?

**Comment by pdehaan** [comment]
Reverted the nodemon version bump and updated package-lock file. But now we should get the <kbd>npm audit</kbd> errors again. If the integration tests pass on nodemon@1 but fail on nodemon@2, we can see if there is a version of nodemon@1 that fixes the high severity module warning.

**Comment by groovecoder** [comment]
I got a nodemon update to pass all checks here: https://github.com/mozilla/blurts-server/pull/1864

**Comment by pdehaan** [comment]
Closing in favor of #1864

**Pull request closed without merging**
