### PR TITLE
Uniform CTA formatting on /about page.

### LINKED ISSUE #1010: German about page is oddly formatted
Note the three columns at the bottom of the page aren't equally spaced. I couldnt reproduce that in other locales, and not sure why German is different:

de_about

---

<details>
<summary>puppeteer l10n scraper</summary>

```js

const pontoonql = require("pontoonql");
const puppeteer = require("puppeteer");

main();

async function main() {
  const urls = [
    {url: "/", slug: "home"},
    {url: "/about", slug: "about"},
    {url: "/breaches", slug: "breaches"},
    {url: "/security-tips", slug: "security-tips"},
    {url: "/?breach=LinkedIn", slug: "breach"},
    {url: "/breach-details/LinkedIn", slug: "breach-details"}
  ];
  const locales = await getStats("firefox-monitor-website", 80);
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setViewport({ width: 1600, height: 1200 });
  for (const {locale} of locales) {
    console.log(`[${locale}]`);
    await page.setExtraHTTPHeaders({ "Accept-Language": locale});
    for (const {url, slug} of urls) {
      const localeUrl = new URL(url, "https://fx-breach-alerts.herokuapp.com/").href;
      const outfile = `tmp/shots/${locale}_${slug}.png`;
      console.log(`  scanning ${localeUrl} to ${outfile}`);
      await page.goto(localeUrl);
      if (slug === "breaches") {
        await page.type(".fuzzy-find-input", "be", {delay: 100});
      }
      const pageHeight = await page.evaluate(() => document.body.scrollHeight);
      await page.screenshot({
        path: outfile,
        type: "png",
        clip: {x:0,y:0,width:1600, height: Math.min(pageHeight, 4000)}
      });
    }
  }
  return process.exit(0);
}

async function getStats(name, limit=80) {
  const stats = await pontoonql("firefox-monitor-website", limit);
  return stats.map(({locale: {code: locale, name}, ...rest}) => ({locale, name, ...rest}));
}
```
</details>

### LINKED ISSUE #1083: Inconsistent link formatting on /about page
## Steps to reproduce

1. Go to https://fx-breach-alerts.herokuapp.com/about
1. Scroll to the bottom of the page and compare the link styling on each of the three links.

### Actual results
The middle link, **Sign up for Alerts**, is bold.

About_Firefox_Monitor

### Expected results
All three links should use the same formatting.
They all look the same on production, https://monitor.firefox.com/about, so I'm guessing this is a recent CSS change.

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
- Restyle the /about page CTAs into buttons instead of links.
- Fix strange formatting of text blocks in more verbose locales (German, specifically).

Fixes #1083
Fixes #1010

### CODE REVIEW

**Comment by pdehaan** [comment]
Code looks good. I can do a more thorough scan once it lands on dev server and maybe run the puppeteer screenshot machine against the /about page in all the supported locales.

For my own near-future reference, here's the current (pre-PR) behavior:

About_Firefox_Monitor

**Comment by pdehaan** [comment]
Merging because I'm curious, and may get bored and check the /about page on all the locales this weekend if I can find some Puppeteer time. I'll file new bugs if I spot anything suspicious with the new UI changes. ❤️

**Comment by lesleyjanenorton** [comment]
Thank you!! I am also curious and still a little mystified as to what was actually causing this (...the wrapping `<h4>` maybe?..). Definitely keep me posted if you find time to Puppeteer!

**Comment by pdehaan** [comment]
FWIW, here's the German version of the /about page, which looks 👌:

de_about

(Puppeteer code is in https://github.com/mozilla/blurts-server/issues/1010#issue-448435421)

**Pull request merged**
