### PR TITLE
pin event-stream-to-3.3.4

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by pdehaan** [comment]
Looks sane, but I think our current usage of **event-stream** is being injected via **npm-run-all** > **ps-tree**, so I don't know how npm will resolve any version bumps in those modules...

/cc @moz-jvehent for his guidance (since I was literally just reading his email)

```sh
$ git rev-parse --short HEAD # 67328e1
$ npm ls event-stream flatmap-stream

blurts-server@0.0.1 /Users/pdehaan/dev/github/mozilla/blurts-server
└─┬ npm-run-all@4.1.3
  └─┬ ps-tree@1.1.0
    └── event-stream@3.3.4
```

**Comment by groovecoder** [comment]
This effectively moves the dependency "up" from `ps-tree` module into our own `package.json` so we can control the version.

**Comment by groovecoder** [comment]
Don't now why Travis is failing, but these tests pass on my local and I'd like to get this in.

**Comment by groovecoder** [comment]
@pdehaan can you check out https://github.com/mozilla/blurts-addon/pull/138 too? Same thing in the other repo.

**Comment by pdehaan** [comment]
@groovecoder See https://github.com/mozilla/blurts-addon/pull/138#discussion_r236759872

**Pull request merged**
