### PR TITLE
Only lint l10n files in GitHub Actions

### PR DESCRIPTION
**Pull request by Vinnl**
The CircleCI job was redundant with the GitHub Actions workflow `reference_linter.yaml`.

See https://github.com/mozilla/blurts-server/pull/3268#issuecomment-1658653500.

### CODE REVIEW

**Review by flodolo — APPROVED** [review]

**Review by mansaj — APPROVED** [review]

**Review by pdehaan — APPROVED** [review]

**Comment by Vinnl** [comment]
@pdehaan I set your branch as the target of this PR, so I can either wait until you've merged your PR, or merge this into your branch - which do you prefer?

**Comment by Vinnl** [comment]
@flodolo I updated this job to run the lint job on _every_ push and PR. This allows us to make it a requirement before merging a branch - do you see any problems with that approach?

**Comment by flodolo** [comment]
> @flodolo I updated this job to run the lint job on _every_ push and PR. This allows us to make it a requirement before merging a branch - do you see any problems with that approach?

It's just that it's going to run a lot, when the patches actually changing localizations are a small minority.

**Comment by Vinnl** [comment]
Cool, that's already what it did in CircleCI, so it's still a net reduction :)

**Pull request merged**
