### PR TITLE
Add target _blank to links in breach card (MNTOR-2895)

### PR DESCRIPTION
**Pull request by flozia**
# References: 
Jira: [MNTOR-2895](https://mozilla-hub.atlassian.net/browse/MNTOR-2895)

# Description

Open breach card links in a new tab or window.

[MNTOR-2895]: https://mozilla-hub.atlassian.net/browse/MNTOR-2895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Vinnl — COMMENTED** [review]
I think we'll also need the `<OpenInNew>` icon. (You can do so by wrapping it in a new component that takes `{ children: ReactNode }`.

**Comment by flozia** [comment]
> I think we'll also need the `<OpenInNew>` icon. (You can do so by wrapping it in a new component that takes `{ children: ReactNode }`.)

The open new icon was [already in there](https://github.com/mozilla/blurts-server/pull/4152/files#diff-1c54685579664551af4b935bc49c87b0656912100596b48c9d77af13f7367efbR469-R472).

**Review by Vinnl — APPROVED** [review]
So sorry, I didn't get that those were two links next to each other!

**Comment by flozia** [comment]
> So sorry, I didn't get that those were two links next to each other!

No worries at all. Ideally, those would be in one either way. I just decided to go for the least inversive change possible after the regression testing.

**Pull request merged**
