### PR TITLE
Recommend tools that foster enabling 2FA

### PR DESCRIPTION
**Pull request by conorgil**
Update 2FA tip to recommend tools and resources that help people enable 2FA on their accounts.

I would much prefer to have the text render actual links rather than URLs, but that requires updating a few things and would also have to be tackled if https://github.com/mozilla/blurts-server/issues/463 moves forward so I'm ignoring that for now.

### CODE REVIEW

**Comment by groovecoder** [comment]
Thanks for the contribution. All content updates will need to be approved or made by @betsymi.

**Comment by conorgil** [comment]
Sounds good. Let me know if there is anything I can do to help.

Also, I forgot to link this to #510.

**Comment by groovecoder** [comment]
Thanks again for the input @conorgil. We probably won't merge this PR as-is, but I'll leave it open to remind us to keep 2FA suggestions & recommendations on the top of our minds. We're planning to run a survey of data classes and protections with users to help us prioritize which protections we will focus on advocating first.

Keep tabs on this repo and you should see when some issues and/or PRs start coming in for 2FA recommendations.

**Comment by groovecoder** [comment]
Closing to clean up our PR queue.

**Comment by conorgil** [comment]
@groovecoder Bummer to see this closed. Can you shed any more light on why it won't be accepted as-is? Is it the specific wording that I suggested, or the specific tools that I recommended? Maybe something else entirely?

Also, can you explain more what you meant by:
> We're planning to run a survey of data classes and protections with users to help us prioritize which protections we will focus on advocating first.

Do you mean that you plan to survey end-users to ask them which protections they care about? I don't think that is what you mean, but it'd be great if you could clarify. Thanks!

**Comment by groovecoder** [comment]
A bit of both.

@betsymi is writing the copy for the site and is in charge of all wording changes. She knows how Firefox words Privacy & Security features across products to keep us consistent, and she also collaborates with our localizers to know which wordings are best for translating into other languages.

Before we recommend any security tools, we also need to review them from a number of angles: privacy, security, legal, brand, etc. Sorry we don't have clear guidelines for how we evaluate them. It may be helpful to draw some up for future recommendations.

We are sending a survey to:

* A broad panel of internet users
* Mozilla staff & community members
* (Potentially) existing Firefox Monitor users (via an email blast?)

That will help us know which recommendations will be the most important for our users.

**Pull request closed without merging**
