### PR TITLE
merge `main` into `localization`

### PR DESCRIPTION
**Pull request by toufali**

### CODE REVIEW

**Comment by flodolo** [comment]
The diff for this one looks surprising? I wouldn't expect changes to the en file for example

**Comment by toufali** [comment]
> The diff for this one looks surprising? I wouldn't expect changes to the en file for example

My thoughts exactly – I'm investigating, but it's possible this might have been a side effect of a rebase.  The diffs are similar to what was merged last week: https://github.com/mozilla/blurts-server/commit/1548f384c972a0355c0ce7d4c393a5731d558b24

**Comment by flodolo** [comment]
Yeah, I just realized that I had similar issues in another project, where rebases cause very confusing diffs.

**Comment by flodolo** [comment]
This diff looks definitely less scary https://github.com/mozilla/blurts-server/compare/localization...main

**Comment by toufali** [comment]
> This diff looks definitely less scary [localization...main](https://github.com/mozilla/blurts-server/compare/localization...main)

Yes -- I believe that's the same diff as the PR we're on (main into localization)?  My plan was to merge this less-scary one first, then hopefully see a much less scary diff going from localization to main 🤞

**Pull request merged**
