### PR TITLE
fix #599: __version__ returns heroku commit on heroku

### LINKED ISSUE #599: Add /__version__ endpoint to Heroku dev/l10n server
It'd be nice if `__version__` also worked on heroku, so we could see which state of l10n is deployed. That question came up in the l10n slack channel, CC @nukeador , @flodolo

_Originally posted by @Pike in https://github.com/mozilla/blurts-server/issues/179#issuecomment-436219980_

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
Sorry @pdehaan we've disabled `master` automatically pushing to heroku because we're keeping the FxA branch on heroku. Will have to wait a while to see this on heroku.

**Comment by pdehaan** [comment]
Not sure if this is possible/easy w/ Heroku deployments, but...

Would we be able to keep the **master** branch deploying to Heroku w/ every commit, and just separate the FxA deployment branch on a separate instance (like //fx-breach-alerts-fxa.herokuapp.com or whatever)?
That way we'd always know if the content on the respective servers is fresh and we wouldn't have to remember if Heroku is point to branch A or branch B.

**Comment by groovecoder** [comment]
We could set up another instance, yeah. To make it more future proof, maybe we could make it https://fx-breach-alerts-future.herokuapp.com ? Or we could make https://blurts-server-master.herokuapp.com and change our `master` branch to deploy to that one? And keep fx-breach-alerts as a PM+UX review instance?

**Comment by groovecoder** [comment]
FWIW I'm setting up https://blurts-server-review.herokuapp.com/ for this purpose. (Last night a Pontoon commit over-wrote `master` onto the heroku server while we were hoping to do UX-engineering review on the FxA branch on it.)

**Comment by pdehaan** [comment]
@groovecoder What is the difference between these two URLs, and when will each one update?

https://fx-breach-alerts.herokuapp.com/
https://blurts-server-review.herokuapp.com/

**Comment by groovecoder** [comment]
https://fx-breach-alerts.herokuapp.com/ - automatically updates on every commit pushed to master
https://blurts-server-review.herokuapp.com/ - updates only when devs push to it manually

Note: until we get SES/email fixed on the -review server, we're using the first server to do the UX+engineering review of FxA.

**Pull request merged**
