### PR TITLE
MNTOR-1321: deprecate unused vars for v2

### PR DESCRIPTION
**Pull request by mansaj**
# References: 
Jira: MNTOR-1321
Figma: n/a

# Description
Deprecate unused vars from v1

# Screenshot (if applicable)

Not applicable.

# How to test
* Delete the following var in `.env`
  *   BREACH_RESOLUTION_ENABLED
  *   EXPERIMENT_ACTIVE
  *   HIBP_RELOAD_BREACHES_TIMER
  *   PAGE_TOKEN_TIMER
  *   PRODUCT_PROMOS_ENABLED
* `npm start`

# Checklist (Definition of Done)
- [x] Localization strings (if needed) have been added.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] I've added or updated the relevant sections in readme and/or code comments
- [ ] I've added a unit test to test for potential regressions of this bug.
- [x] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [x] All acceptance criteria are met.
- [x] Jira ticket has been updated (if needed) to match changes made during the development process.
- [x] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

### CODE REVIEW

**Review by toufali — APPROVED** [review]
Thanks for getting this started!  Would you consider this just a first pass?  I bet there are more we could remove that don't apply to Refresh -- for example the VPN GeoIP stuff...

**Comment by mansaj** [comment]
> Thanks for getting this started! Would you consider this just a first pass? I bet there are more we could remove that don't apply to Refresh -- for example the VPN GeoIP stuff...

I see the GeoIP ones (as optionals). I thought we are adding the VPN ads back in. Would we need to eventually add back the location detector?

**Review by toufali — COMMENTED** [review]
I _think_ we can also get rid of `EDUCATION_VIDEO_URL_RELAY`

The `FX_REMOTE_*` – should they be moved to optional at least?  I don't believe they're used in Refresh?

Not sure if we refactored the ones requiring `HIBP_THROTTLE_*`

Not sure what `LIVE_RELOAD` is 😅

**Comment by mansaj** [comment]
> I _think_ we can also get rid of `EDUCATION_VIDEO_URL_RELAY`
> 
> The `FX_REMOTE_*` – should they be moved to optional at least? I don't believe they're used in Refresh?
> 
> Not sure if we refactored the ones requiring `HIBP_THROTTLE_*`
> 
> Not sure what `LIVE_RELOAD` is 😅

Deleted `EDUCATION_VIDEO_URL_RELAY`, we need the rest but moved `FX_REMOTE` to optional... we will need those for the future

**Comment by mansaj** [comment]
Deferring changes to `env-dist` because it impacts the database migration step of our CICD at the moment. We would want to make all the changes when we deprecate v1 from the repository

**Pull request merged**
