### PR TITLE
Restore "see-all-breaches" string.

### PR DESCRIPTION
**Pull request by lesleyjanenorton**

### CODE REVIEW

**Comment by flodolo** [comment]
Is this only used in emails? Should it live in emails.ftl?

**Comment by lesleyjanenorton** [comment]
@flodolo This string is only being used in emails and would be better housed in `emails.ftl` but I noticed that it is still available in `locales/cak/app.ftl`. If it can live in `emails.ftl` though I will move it.

**Comment by flodolo** [comment]
It's still in cak because they're behind, and Pontoon never had a chance to clean up the file. Ignore cak ;-)

**Comment by groovecoder** [comment]
code & spot-check look good.

**Pull request merged**
