### PR TITLE
Add website link on breach detail pages.

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
I am a little bit leery of linking users to some of these websites (and I wonder if this link will be perceived somehow as an endorsement or assurance of the site's authenticity/safety) but I can't think of a way of doing this without running a considerable number of checks before deciding whether or not to surface the link.

### CODE REVIEW

**Comment by changecourse** [comment]
Just as it relates to sensitive breaches, or is it not that simple?

**Comment by lesleyjanenorton** [comment]
@changecourse  Mostly because we know this solution will result in some edge-case broken links if the site no longer exists or doesn't support HTTPS. For the majority of websites, it won't be an issue and we're assigning a "nofollow" value to the `rel` attribute so at least the more dubious sites won't get an SEO boost from our linking to them.

**Comment by pdehaan** [comment]
### With `breach.Domain`:

_Apollo

---

### Without `breach.Domain`:

_AntiPublic

---

<details>
<summary>puppeteer-domain-lint.js (WIP)</summary>

```js
"use strict";

const got = require("got")
const puppeteer = require("puppeteer");

main();

async function main(baseUri="http://localhost:6060/") {
  const breaches = await getBreaches(baseUri);
  const breachNames = breaches.map(breach => breach.Name);

  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  for (const name of breachNames) {
    try {
      await getBreachDetails(name, page, baseUri);
    } catch (err) {
      console.error(name, "=>", err.message);
    }
  }
  browser.close();
}

async function getBreaches(baseUri) {
  const breachUri = new URL("/hibp/breaches", baseUri).href;
  const res = await got(breachUri, {json: true});
  return res.body; //.slice(0, 40);
}

async function getBreachDetails(name, page, baseUri) {
  const breachDetailUri = new URL(`/breach-details/${name}`, baseUri).href;
  await page.goto(breachDetailUri, {waitUntil: "networkidle0"});
  await page.screenshot({path: `tmp/_${name}.png`});
  try {
    const breachDomainLinkHref = await page.$eval("a.breach-domain-link", el => el.href);
    // out: "Checking http://localhost:6060/breach-details/500px ... https://www.500px.com/"
    console.log(`Checking ${breachDetailUri} ... ${breachDomainLinkHref}`);
  } catch (err) {
    // out: "Missing breach.Domain for 2844Breaches"
    console.error(`Missing breach.Domain for ${name}`);
  }
}

/*
Checking http://localhost:6060/breach-details/000webhost ... https://www.000webhost.com/
Checking http://localhost:6060/breach-details/126 ... https://www.126.com/
Checking http://localhost:6060/breach-details/17Media ... https://www.17app.co/
Checking http://localhost:6060/breach-details/17173 ... https://www.17173.com/
Missing breach.Domain for 2844Breaches
Checking http://localhost:6060/breach-details/2fast4u ... https://www.2fast4u.be/
Checking http://localhost:6060/breach-details/500px ... https://www.500px.com/
...
*/
```
</details>

**Comment by groovecoder** [comment]
Merging/clearing some outstanding PRs for a deploy this week and to prepare for a more extensive fix for case-sensitive subscriptions.

**Pull request merged**
