### PR TITLE
Add eslint-plugin-jsdoc

### PR DESCRIPTION
**Pull request by flozia**
# References: 

Putting this up as a draft in response to https://github.com/mozilla/blurts-server/pull/2838#discussion_r1108802218 for discussion.

# Description

This enables all the “recommended” rules by `eslint-plugin-jsdoc`. Are we all in favor of adding these rules, just a subset — or not at all?

### CODE REVIEW

**Comment by Vinnl** [comment]
Looks like you forgot to commit the updated the lockfile. But yes, I am generally in favour of avoiding tedious discussions about individual linting rules, and just adopting recommended sets with general principles. (So for example, on Relay we enable rules that help with catching potential bugs, but leave styling issues to Prettier so we don't have to manually fix those.)

**Review by toufali — APPROVED** [review]
Not familiar with this plugin, but in favor of it, assuming it kicks in when we've opted in to a JSDoc block (and doesn't mandate we add one for every function 😅). 

I would appreciate an error if I've specifically used JSDoc syntax that is broken, and simple warnings for suggested-but-not-required practice.  (Maybe these are already "sensible" defaults?)

**Review by rhelmer — APPROVED** [review]

**Comment by flozia** [comment]
> […] , but leave styling issues to Prettier so we don't have to manually fix those.)

@Vinnl Seems like styling-related lining is not included in the [set of recommend rules](https://github.com/gajus/eslint-plugin-jsdoc#configuration).

> Not familiar with this plugin, but in favor of it, assuming it kicks in when we've opted into a JSDoc block (and doesn't mandate we add one for every function 😅).
>
> I would appreciate an error if I've specifically used JSDoc syntax that is broken, and simple warnings for suggested-but-not-required practice. (Maybe these are already "sensible" defaults?)

@toufali Good point. I disabled the rule `require-jsdoc` so that the plugin only kicks in if we opt for a comment. I did not find a “sensible defaults” option and it looks like we’d have to set more restrictive rules ourselves. Let’s do that for individual rules as we encounter them.

**Comment by Vinnl** [comment]
> Seems like styling-related lining is not included in the [set of recommend rules](https://github.com/gajus/eslint-plugin-jsdoc#configuration).

I didn't mean that as a specific suggestion, just an example of what "general principles" may look like. So this is perfect :)

**Pull request merged**
