### PR TITLE
MNTOR-1004, MNTOR-1004 - backend settings screen for v2 and refactor email utility

### PR DESCRIPTION
**Pull request by rhelmer**
This is still a work-in-progress, need to finish the following:

- [ ] add unit tests (depends on https://github.com/mozilla/blurts-server/pull/2759)
- [ ] resolve FIXME and TODOs
- [x] implement CSRF (depends on https://github.com/mozilla/blurts-server/pull/2751)

### CODE REVIEW

**Comment by toufali** [comment]
Thanks for putting this up!  I haven't gotten a chance to review yet, but just leaving a note to say I can work with you when I return to resolve the CircleCI stuff if you need.  Also, we should probably sync our formatting settings to make code reviews easier.

**Review by toufali — COMMENTED** [review]
Sorry for the delayed eyes on this – per your Slack message it sounds like you're breaking the PR up which sounds good!  One note before the split:

Not sure if the images you're using are FPO, but I'd like to coalesce on .webp and .svg formats if possible.  Figma has .svg export for pure vector stuff (be careful they don't sneak any binary files into the code!)  As for .webp we're not so lucky yet.  I added a script to convert those in-place: `npm run convert:webp`.  There's more to it than that (the script path is incorrect for one!)  But just wanted to flag and happy to discuss further with you and @flozia .  Apologies, I intended this to be in the README but hadn't got around to it yet.

**Comment by rhelmer** [comment]
> Sorry for the delayed eyes on this – per your Slack message it sounds like you're breaking the PR up which sounds good! One note before the split:
> 
> Not sure if the images you're using are FPO, but I'd like to coalesce on .webp and .svg formats if possible. Figma has .svg export for pure vector stuff (be careful they don't sneak any binary files into the code!) As for .webp we're not so lucky yet. I added a script to convert those in-place: `npm run convert:webp`. There's more to it than that (you need to install stuff and the script path is incorrect!) But just wanted to flag and happy to discuss further with you and @flozia . Apologies, I intended this to be in the README but hadn't got around to it yet.

Thanks! I split the front-end parts out to https://github.com/mozilla/blurts-server/pull/2763 and added this to a comment about the known issues https://github.com/mozilla/blurts-server/pull/2763#issuecomment-1381338930

**Comment by rhelmer** [comment]
I'm going to close this and re-open for a few reasons:

1. GH Actions (which run the V2 unit tests) don't seem to run on forks (I think we can allow for team members?)
2. I can further split out email from the settings/api changes, since I think email is basically ready to go and I expect settings to have a longer review cycle (and the test situation there is more complex, it expects a test DB which we talked about moving away from in eng meeting today)

**Comment by rhelmer** [comment]
NOTE: I've split this out to https://github.com/mozilla/blurts-server/pull/2773 and https://github.com/mozilla/blurts-server/pull/2772

**Pull request closed without merging**
