### PR TITLE
Bug 1855173 - CI: Run probe-scraper push action on push and on PRs

### PR DESCRIPTION
**Pull request by badboy**
# References: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1855173

### CODE REVIEW

**Review by rhelmer — APPROVED** [review]
lgtm, thanks! This failing test is because outside contributors don't have access to the secrets needed, working on fixing that.

**Comment by Dexterp37** [comment]
> lgtm, thanks! This failing test is because outside contributors don't have access to the secrets needed, working on fixing that.

@rhelmer thanks for letting me know! Please feel free to merge this (I can't) or create a new PR with the same code and merge it if it's simpler !

**Comment by rhelmer** [comment]
Filed https://mozilla-hub.atlassian.net/browse/MNTOR-2215 to really fix this, for the moment I'm going to cherry-pick this onto a different branch and get it landed that way. Sorry for the hassle!

**Comment by rhelmer** [comment]
Closing in favor of https://github.com/mozilla/blurts-server/pull/3472

**Pull request closed without merging**
