### PR TITLE
Add missing zero form for two Czech strings

### PR DESCRIPTION
**Pull request by MikkCZ**
https://bugzilla.mozilla.org/show_bug.cgi?id=1443551

CCing @jrychly who's working on the project too, to know what causes the warnings in Pontoon.

### CODE REVIEW

**Comment by flodolo** [comment]
It is, but you can fix it in Pontoon directly if you want. Did you give it a try?

**Comment by MikkCZ** [comment]
Trying to switch to FTL rich editor for these two strings only shows an error about missing reference to `{no-breaches}`. For `featured-breach-results` it worked.

**Comment by flodolo** [comment]
Temporarily copy `{no-breaches}` into one of the forms, switch to syntax and paste your FTL.

**Comment by MikkCZ** [comment]
Nice life hack. It did work, thank you!

**Pull request closed without merging**
