### PR TITLE
Update to fluent 0.10

### PR DESCRIPTION
**Pull request by stasm**
Please update to the newest version of `fluent`. It supports the new features of the Fluent Syntax, introduced in [versions 0.7 and 0.8](https://github.com/projectfluent/fluent/releases) of the spec. The `fluent` package on npm is [versioned independently](https://github.com/projectfluent/fluent.js/blob/master/fluent/CHANGELOG.md) of the spec versions, but the gist is that `fluent` 0.10 supports the most recent syntax spec.

This is important to us because we'd like to roll out the support for these new features in Pontoon soon. Once available, localizers will be free to use them in their translations. I'd like to make sure `blurts-server` is ready for any such updated translations.

I tested this locally briefly, i.e. without creating a DB nor connecting to HIBP. The landing page and some error pages showed up localized as expected. Thanks!

### CODE REVIEW

**Comment by stasm** [comment]
I'm seeing two test failures in https://travis-ci.org/mozilla/blurts-server/jobs/472607359#L1999 but they don't look related to the Fluent update. @groovecoder, are these failures known (perhaps intermittent)?

```
 FAIL  tests/controllers/hibp.test.js (7.944s)
  ● notify POST for subscriber with no signup_language should default to en
    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
      91 | 
      92 | 
    > 93 | test("notify POST for subscriber with no signup_language should default to en", async () => {
         | ^
      94 |   jest.mock("../../email-utils");
      95 |   jest.mock("../../hibp");
      96 |   EmailUtils.sendEmail = jest.fn();
      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Object.test (tests/controllers/hibp.test.js:93:1)
 PASS  tests/controllers/user.test.js
 FAIL  tests/db.test.js
  ● addSubscriber with existing email updates updated_at
    TypeError: Cannot read property 'addExpectationResult' of undefined
      at Env.fail (node_modules/jest-jasmine2/build/jasmine/Env.js:534:24)
```

**Comment by groovecoder** [comment]
The Timeout is a flaky failure. 😢 

The other is not expected. I'll dig into them tomorrow.

Will this update break our existing `.ftl` files? Is the new syntax backwards-compatible?

**Comment by pdehaan** [comment]
/cc @stasm 

Re: backward compatibility,

It looks like Variants are deprecated as of fluent@0.8 and will be removed; per https://projectfluent.org/fluent/guide/variants.html

As far as I can tell, some of the locales are possibly still using them (if I'm reading it correctly):

https://github.com/mozilla/blurts-server/blob/f40b4fba94243adca47d96c847318edd3989da10/locales/ru/app.ftl#L11-L16

Would that cause any problems, or would we have to get the Russian l10n updated before we can switch over to v0.10

**Comment by stasm** [comment]
That's a good question, thanks for asking. Short answer is: all should be fine.

Fluent Syntax 0.8 (the spec) as well as `fluent` 0.10 (the npm package) still support variants to make upgrading easier. We'll remove them when we're confident no projects use them anymore. Once Monitor upgrades to `fluent` 0.10, @flodolo or I will coordinate with the Russian team and update their translations in Pontoon. Alternatively, I can do that in this PR. @flodolo, do you have a preference?

**Comment by flodolo** [comment]
Doing it in the PR makes sense to me. We should cc Alexander to make sure
he is aware, and that we'll do it for Firefox too as soon as we are ready.

(on my phone, don't have access to Github)

Il giorno mar 8 gen 2019, 08:44 Staś Małolepszy <notifications@github.com>
ha scritto:

**Comment by pdehaan** [comment]
@groovecoder Now that v3.1.9 is tagged and en route to stage/prod, can you give this a final review and push to Heroku so we can test it out? 

Plus, I can see if https://github.com/pdehaan/blurts-puppeteer-l10n still works and try taking screenshots of the homepage+breach pages for each of the 80%+ locales and try a quick visual scan to see if everything still looks 👌.

**Comment by groovecoder** [comment]
Let me make sure v3.1.9 gets all the way to prod before I merge this.

**Comment by stasm** [comment]
Hey @unghost, would you mind taking a look at https://github.com/mozilla/blurts-server/pull/668/commits/3964d120a580079b5559dc147a42ee3235ade347 in this PR? No action is needed but I wanted to make sure you're aware of this planned change in the localization. It will auto-sync in Pontoon when this PR lands.

We're replacing variant lists with a new feature in Fluent called parameterized terms. You can read about them in the [Syntax 0.8 release notes](https://github.com/projectfluent/fluent/releases/tag/v0.8.0) (third bullet point) and in the [Fluent Syntax Guide](https://projectfluent.org/fluent/guide/terms.html). If you prefer a different name for the `case` parameter, please let me know. Thanks!

**Comment by unghost** [comment]
> Hey @unghost, would you mind taking a look at [3964d12](https://github.com/mozilla/blurts-server/commit/3964d120a580079b5559dc147a42ee3235ade347) in this PR? 
LGTM.

**Comment by groovecoder** [comment]
FWIW Travis CI errors here are the same as https://github.com/mozilla/blurts-server/issues/703.

**Comment by stasm** [comment]
@groovecoder Yes, thank you.

**Pull request merged**
