### PR TITLE
add relay as a recommendation

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Review by flodolo — COMMENTED** [review]
Can you help me understand why two sets of identical messages? How does the context change, i.e. are they used in different places?

**Comment by groovecoder** [comment]
> Can you help me understand why two sets of identical messages? How does the context change, i.e. are they used in different places?

Sorry, I thought I had to use 2 different messages to show this in 2 separate places.

I consolidated it down to 1 message.

**Comment by groovecoder** [comment]
The difference in context is only on the back-end. This message is shown as a recommendation on a breach detail page:

Some breaches included "priority" data categories, so we have specific recommendations:

image

For breaches that have no priority data classes, we show "general" recommendations:

image

So the contextual difference to the end user is very small. It's mostly a technical detail of which recommendations we show on which breaches.

**Review by flodolo — APPROVED** [review]

**Comment by maxxcrawford** [comment]
Added icon for the new recommendation: 
image

**Pull request merged**
