### PR TITLE
toLowerCase the email before hashing

### PR DESCRIPTION
**Pull request by nhnt11**
Emails are not case sensitive so the service shouldn't be either.

### CODE REVIEW

**Comment by pdehaan** [comment]
It _looks_ logical...
For sanity checking sake, here's our current usage of `.toLowerCase()` and `.toUpperCase()` in this repo:

```sh
$ git grep "to.*erCase()"

hibp.js:    const sha1Prefix = sha1.slice(0, 6).toUpperCase();
hibp.js:        if (sha1.toUpperCase() === sha1Prefix + breachedAccount.hashSuffix) {
public/js/monitor.js:  return re.test(String(val).toLowerCase());
scripts/make-sha1-hashes.js:  shasum.update(trimmedString.toLowerCase());
```

**Comment by lesleyjanenorton** [comment]
Looks good to me but are we sure it's necessary? I tried a few emails with and without the toLowerCase and all came back with the expected results but that could also be because they're cached (reminiscing about the .toUpperCase bug).

**Comment by nhnt11** [comment]
I made it toUpperCase the hash before returning as well.

Let's be consistent with this. FWIW, current production deployment shows no results for scanning my email address in upper case, which is wrong.

**Comment by lesleyjanenorton** [comment]
Great catch @nhnt11 . Merging.

**Pull request merged**
