### PR TITLE
fix circle

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by pdehaan** [comment]
Do we need Circle-CI _and_ Travis-CI? Or are we getting rid of Travis?

**Comment by groovecoder** [comment]
Probably we can eventually get rid of Travis. Right now I'm just trying to get Circle going so it can publish the containers to the Mozilla registry for deployment.

**Comment by groovecoder** [comment]
Hmm ... this fixes circle, but it isn't doing the deployment to docker hub? @Micheletto - any ideas why not?

**Comment by Micheletto** [comment]
> Hmm ... this fixes circle, but it isn't doing the deployment to docker hub? @Micheletto - any ideas why not?

I think you need to add Environment Variables to your build parameters: https://circleci.com/docs/1.0/environment-variables/

**Pull request merged**
