### PR TITLE
Add logos for recent breaches.

### LINKED ISSUE #1155: Missing logos for recent breaches
```js
$ npx pdehaan/blurts-missing-logos

[
  { "url": "https://monitor.firefox.com/img/logos/AnimePlanet.png", "err": 404 },
  { "url": "https://monitor.firefox.com/img/logos/Artvalue.png", "err": 404 },
  { "url": "https://monitor.firefox.com/img/logos/ClashOfKings.png", "err": 404 },
  { "url": "https://monitor.firefox.com/img/logos/EpicNPC.png", "err": 404 },
  { "url": "https://monitor.firefox.com/img/logos/Snail.png", "err": 404 }
]
```

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
Fixes #1155

### CODE REVIEW

**Comment by lesleyjanenorton** [comment]
I renamed ArtValue.png to Artvalue.png and it seemed (locally) like git picked up on the change but it doesn't look like the casing change is reflected here?

**Comment by pdehaan** [comment]
re: ArtValue.png,

Not sure if you'll need to rename the file to something different (not just case, ie: Artvalue.tmp) then Artvalue.png. Or see if [`git mv`](https://git-scm.com/docs/git-mv) will do the trick.

**Comment by lesleyjanenorton** [comment]
@pdehaan thank you! The .tmp thing worked but it took two commits. `git mv` is what I tried initially and I'm still not sure why it didn't work.

**Comment by pdehaan** [comment]
Except now I think we have ArtValue and Artvalue, which means one's an orphan.

**Comment by pdehaan** [comment]
Nevermind. My bad, I see that the ArtValue is deleted in this PR. Merging.

**Comment by pdehaan** [comment]
Confirmed no missing logos on dev server:

```js
$ npx pdehaan/blurts-missing-logos

[]
```

Also, I updated the [**pdehaan/blurts-missing-logos**](https://github/com/pdehaan/blurts-missing-logos) script to check the _dev_ server by default instead of checking production (since sometimes logos land on dev, but don't hit prod right away &mdash; and we want to avoid false positives).

If you want to verify the missing _production_ logos, you can revert to the old behavior by passing a `SERVER` env variable, a la;

```sh
$ SERVER=https://monitor.firefox.com npx pdehaan/blurts-missing-logos

[
  {
    "url": "https://monitor.firefox.com/img/logos/AnimePlanet.png",
    "err": 404
  },
  ...
]
```

**Pull request merged**
