### PR TITLE
Revert "Merge pull request #4686 from mozilla/mntor-3201"

### PR DESCRIPTION
**Pull request by mansaj**
This reverts commit f97bac257b496aeab04c554be3cd636dcf80c563, reversing changes made to 74087749c2b287983beaf66bc28a858acc75917c.

# References:

Jira: MNTOR-
Figma:

# Description

# Screenshot (if applicable)

Not applicable.

# How to test

# Checklist (Definition of Done)

- [ ] Localization strings (if needed) have been added.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] I've added or updated the relevant sections in readme and/or code comments
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] If this PR implements a feature flag or experimentation, the Ship Behind Feature Flag status in Jira has been set
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

### CODE REVIEW

**Comment by flodolo** [comment]
This is disruptive, because the strings are already being translated (and with this merged we would be missing 3).

Why the back-out? This is the 2nd time it happened recently, while I don't remember being it so frequent earlier.

**Comment by mansaj** [comment]
@flodolo we aren't going to actually merge this in, this is just for prod release today (release branch)
I'm going to close this PR after

**Comment by mansaj** [comment]
@flodolo similarly with the other 2 PR reverts, I'll revert the reverts after our prod goes out

**Comment by mansaj** [comment]
@flodolo actually is it ok if we do merge it in and have it reverted later today? 
Our CI is set up in a way that only `main` gets build, so these changes that need to be backed out will have to hit main first

**Pull request closed without merging**
