### PR TITLE
MNTOR-2125: only mark subscriber breach as resolved when all emails are marked as fixed

### PR DESCRIPTION
**Pull request by mansaj**
# References: 
Jira: MNTOR-2125
Figma: 

# Description
The correct behavior should be:
* when any 0-1/2 common breaches is fixed in the old UI, the new UI should still show the breach as active
* only when 2/2 common breaches are fixed in the old UI, the new UI should reflect the breach as being fixed

This bug is not going to be relevant when the redesign launches, as users won’t have an option to select an email address anymore, but I’ll put in a fix for it for now

# Screenshot (if applicable)

Not applicable.

# How to test
1.  On the current version resolve one of the common breaches on the primary account;
2. Refresh the redesigned version of the dashboard and observe the “Fixed” tab;
3. Go back to the current dashboard and uncheck the previously resolved breach;
4. Select the secondary email from the current dashboard;
5. Proceed to fix one of the common breaches;
6. Refresh the redesigned dashboard and observe the “Fixed” tab
7. Fix the common breach for both emails
8. Observe in new UI 

# Checklist (Definition of Done)
- [ ] Localization strings (if needed) have been added.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] I've added or updated the relevant sections in readme and/or code comments
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

### CODE REVIEW

**Review by Vinnl — COMMENTED** [review]
Hmm, I'm having some trouble reproducing/understanding what the bug is. I tried the following on `main`:

- I added the email addresses test@mailinator.com and test2@mailinator.com. Both are in the Luxottica breach.
- I then resolved all types of data in the test2@mailinator.com breach (see screenshot below), while keeping them unchecked for test@mailinator.com
- I then visited the new design, but saw it still listed under the "Action needed" tab, whereas from the PR description I understand the bug should be that it's under the "Fixed" tab?

image

image

**Comment by mansaj** [comment]
> Hmm, I'm having some trouble reproducing/understanding what the bug is. I tried the following on `main`:
> 
> * I added the email addresses [test@mailinator.com](mailto:test@mailinator.com) and [test2@mailinator.com](mailto:test2@mailinator.com). Both are in the Luxottica breach.
> * I then resolved all types of data in the [test2@mailinator.com](mailto:test2@mailinator.com) breach (see screenshot below), while keeping them unchecked for [test@mailinator.com](mailto:test@mailinator.com)
> * I then visited the new design, but saw it still listed under the "Action needed" tab, whereas from the PR description I understand the bug should be that it's under the "Fixed" tab?
> 
> image
> 
> image

This is the correct behavior, only when 2/2 are resolved, it should show up as fixed in the new UI

**Comment by Vinnl** [comment]
@mansaj 

> This is the correct behavior, only when 2/2 are resolved, it should show up as fixed in the new UI

But this was on `main`, so if that's showing the correct behaviour, why is this PR needed?

**Comment by mansaj** [comment]
> @mansaj
> 
> > This is the correct behavior, only when 2/2 are resolved, it should show up as fixed in the new UI
> 
> But this was on `main`, so if that's showing the correct behaviour, why is this PR needed?

@Vinnl Oh good question.. this is a tricky one.. took a while to figure out haha. You can also read about the QA's findings.
The issue is that this behavior is intermittent. Essentially before this PR, if the first email is resolved, then in the new UI, the breach is marked as resolved regardless of what other emails say. I'm not sure if the order to determine the "first" is very predictable, either. 

This PR is meant to fix the logic to consider all emails

**Review by Vinnl — APPROVED** [review]
Heh OK, so unfortunately I couldn't reproduce, and I'm not entirely sure what's going on here, but it looks sensible enough.

**Pull request merged**
