### PR TITLE
Add D3Scene and SocialEngineered logos.

### PR DESCRIPTION
**Pull request by lesleyjanenorton**

### CODE REVIEW

**Comment by pdehaan** [comment]
| Name | Logo |
|:-----|:-----|
| D3Scene | Firefox_Monitor |
| SocialEngineered | Firefox_Monitor |

Interestingly, the Logo is there:
https://fx-breach-alerts.herokuapp.com/img/logos/D3Scene.png

But it's not rendering like I expected. Looking at the source on the dev server, it looks like it may be a D3scene vs D3Scene issue, and the server OS is case sensitive:

```html
<img alt="" class="breach-logo lazy-loaded" data-src="/img/logos/D3scene.png" src="/img/logos/missing-logo-icon.png">
```

https://haveibeenpwned.com/api/v2/breach/D3scene

But sadly we removed our [/hibp/breaches](https://fx-breach-alerts.herokuapp.com/hibp/breaches) endpoint, so I can't easily inspect what our modified HIBP data structure is.

**Comment by lesleyjanenorton** [comment]
Thank you for catching this @pdehaan . Should be fixed in #1098. Was the removal of that endpoint intentional? The error message I get when I land there looks like a handlebars helper error.

**Comment by pdehaan** [comment]
> Was the removal of that endpoint intentional? The error message I get when I land there looks like a handlebars helper error.

Intentional per https://github.com/mozilla/blurts-server/commit/a24f3d2205a0ae909d0b63d5b9acfe2e00294dd0 commit and https://github.com/mozilla/blurts-server/issues/1008#issuecomment-495758202.

But unfortunately that also broke virtually every script/tool I've written for blurts-server, since it always expected a JSON blob of breaches at that URL. Although I managed to refactor most of my scripts to use the upstream HIBP API v2 endpoints, and then redid all the logic around our breach logo naming or DataClasses modifying, etc.

**Comment by pdehaan** [comment]
Confirmed.

Firefox_Monitor

**Pull request merged**
