### PR TITLE
add npmrc to strictly enforce node engine before install

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Review by pdehaan — CHANGES_REQUESTED** [review]
YAY! (fails on < node@10)

```sh
npm i
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for blurts-server@0.0.1: wanted: {"node":"10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm ERR! notsup Not compatible with your version of node/npm: blurts-server@0.0.1
npm ERR! notsup Not compatible with your version of node/npm: blurts-server@0.0.1
npm ERR! notsup Required: {"node":"10"}
npm ERR! notsup Actual:   {"npm":"6.13.4","node":"8.17.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pdehaan/.npm/_logs/2020-11-05T21_25_08_537Z-debug.log
```

Not so yay (fails on > node@10)

```sh
nvm use 14
Now using node v14.15.0 (npm v6.14.8)

npm i
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for blurts-server@0.0.1: wanted: {"node":"10"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm ERR! notsup Not compatible with your version of node/npm: blurts-server@0.0.1
npm ERR! notsup Not compatible with your version of node/npm: blurts-server@0.0.1
npm ERR! notsup Required: {"node":"10"}
npm ERR! notsup Actual:   {"npm":"6.14.8","node":"14.15.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pdehaan/.npm/_logs/2020-11-05T21_25_22_113Z-debug.log
```

Per https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines, looks like we can use semver range operators and do something like this (which will let me/CI still use Node 12 or 14 or whatever is LTS):

```js
  "engines": {
    "node": ">=10"
  },
```

**Comment by pdehaan** [comment]
Also, lets update root README and do a version bump on node reference:

> Node 8+ (with npm)

**Comment by groovecoder** [comment]
Updated README. Going to keep it strict to 10 to keep us locked in sync with what's in the Dockerfile and goes to production.

**Review by pdehaan — APPROVED** [review]
Works for me. And doesn't look like we'll have to worry about Node 10.x EOL until Apr 30 2021, per https://nodejs.org/en/about/releases/.

**Pull request merged**
