### PR TITLE
Reinstate /hibp/breaches endpoint.

### LINKED ISSUE #1008: "fn is not a function" error on dev /hibp/breaches endpoint
https://fx-breach-alerts.herokuapp.com/hibp/breaches

I use our endpoint to scrape the breach list, but I guess I've always used the monitor.firefox.com prod link, and maybe nothing internally uses the /hibp/breaches endpoint which is why we havent noticed this throwing an error.

https___fx-breach-alerts_herokuapp_com_hibp_breaches

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
Fixes #1008

### CODE REVIEW

**Comment by groovecoder** [comment]
Interesting. This is/was just a proxy for https://haveibeenpwned.com/api/v2/breaches right? Does your script want to make sure *our* environment has all the breaches? Or can your script use the HIBP endpoint directly?

**Comment by groovecoder** [comment]
Even if we decide to remove our own endpoint, we should removing [the corresponding code from `routes/hibp.js`](https://github.com/mozilla/blurts-server/blob/master/routes/hibp.js#L9) too.

**Comment by pdehaan** [comment]
> This is/was just a proxy for [haveibeenpwned.com/api/v2/breaches](https://haveibeenpwned.com/api/v2/breaches) right?

IIRC, it returned a modified version of the upstream HIBP breach data (where we tweak the `.DataClasses[]` and `.LogoPath`).

**Comment by groovecoder** [comment]
Oh yeah, we do some customization to the data. Sounds good to restore.

**Pull request merged**
