### PR TITLE
Ducks Unlimited Logo

### PR DESCRIPTION
**Pull request by codemist**
Preview
DucksUnlimited

### CODE REVIEW

**Comment by maxxcrawford** [comment]
@codemist Could you make it to where it's just the head? So that there's no BG color? 
image

**Review by maxxcrawford — CHANGES_REQUESTED** [review]
@codemist Could you make it to where it's just the head? So that there's no BG color? [Like this image](https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Ducks_Unlimited_logo.svg/1200px-Ducks_Unlimited_logo.svg.png)

**Comment by pdehaan** [comment]
#quackquack

**Review by maxxcrawford — APPROVED** [review]
At what time does a duck wake up? **At the quack of dawn.**

**Review by pdehaan — APPROVED** [review]
Thanks!

**Comment by pdehaan** [comment]
Verified on prod

Firefox_Monitor

**Pull request merged**
