### PR TITLE
Update the URL for the VPN

### PR DESCRIPTION
**Pull request by rlr**
The VPN moved to vpn.mozilla.org. We miss the traffic.

### CODE REVIEW

**Comment by groovecoder** [comment]
I think the real fix is to fix #1766 with #1767. I tagged @lesleyjanenorton to see how much work it might be to update the promo template logic to include 2 CTAs.

**Comment by lesleyjanenorton** [comment]
@groovecoder  I can get this done today but just need to know 1.) What are the two CTAs 2.) What are the circumstances that determine when we want to show one CTA instead of the other?

**Comment by rlr** [comment]
I agree. This was meant just to be a stop gap for the real fix. We can close this.

**Comment by lesleyjanenorton** [comment]
Just opened #1771 which adds the copy for the new Mozilla VPN / FPN recommendation. We can update the templates to use the new string and two CTAs once they have been localized.

**Pull request closed without merging**
