### PR TITLE
Add breach logos

### PR DESCRIPTION
**Pull request by maxxcrawford**
Logo previews: 

DevilTorrents

Aimware

PayHere

### CODE REVIEW

**Comment by maxxcrawford** [comment]
@flodolo Please disregard review request. Bad rebase had additional commits on it. 🙈

**Comment by pdehaan** [comment]
Ignoring, but... nit: babynames logo is W: 115px | H: 115px (vs preferred 150&times;150px)

**Review by pdehaan — APPROVED** [review]

**Comment by maxxcrawford** [comment]
@pdehaan I trashed my original commit bc it was diff'd out with 100+ files bc I did base it on `main`

**Comment by pdehaan** [comment]
Verified on prod:
Screen Shot 2022-05-03 at 1 08 50 PM

**Pull request merged**
