### PR TITLE
Optimized breach logos

### PR DESCRIPTION
**Pull request by maxxcrawford**
Revised logos: 

| Name | Image Preview |
|---|---| 
| LinuxMint | LinuxMint |
| AcneOrg | AcneOrg |
| Comcast | Comcast |
| PixelFederation | PixelFederation |
| CrossFire | CrossFire |
| CrackCommunity | CrackCommunity |
| LOTR | LOTR |
| COMELEC | COMELEC |
| Smogon | Smogon |
| Parapa | Parapa |
| LizardSquad | LizardSquad |
| EpicGames | EpicGames |
| Edmodo | Edmodo |
| CannabisForum | CannabisForum |
| ArmyForceOnline | ArmyForceOnline |

### CODE REVIEW

**Comment by pdehaan** [comment]
Actually, looks like there are 3 JPEG files in that ./public/img/logos/* directory:

- [/public/img/logos/**LizardSquad.jpg**](https://github.com/mozilla/blurts-server/blob/master/public/img/logos/LizardSquad.jpg)
- [/public/img/logos/**SvenskaMagic.jpg**](https://github.com/mozilla/blurts-server/blob/master/public/img/logos/SvenskaMagic.jpg)
- [/public/img/logos/**Warmane.jpg**](https://github.com/mozilla/blurts-server/blob/master/public/img/logos/Warmane.jpg)

**Comment by pdehaan** [comment]
Unrelated, but I like to periodically check in... With this PR merged, it looks like we'd have only 5 logos that are over 10KB:

LOGO | WIDTH | HEIGHT | SIZE | &nbsp;
:-----|------:|-------:|-----:|-----
./public/img/logos/DDO.png | 225 | 91 | 13.44 KB | :warning:
./public/img/logos/Minefield.png | 143 | 169 | 11.72 KB | :warning:
./public/img/logos/MangaTraders.png | 400 | 92 | 10.9 KB | :warning:
./public/img/logos/Warmane.png | 95 | 115 | 10.18 KB | :warning:
./public/img/logos/FoxyBingo.png | 298 | 113 | 10.07 KB | :warning:

```js
const fs = require("fs");

const filesize = require("filesize");
const glob = require("glob");
const sizeOf = require("image-size");

main();

async function main(
  logoPath = "./public/img/logos/*.png",
  maxSize = 10 * 1024 // 10KB
) {
  const logos = glob
    .sync(logoPath)
    .map(logo => {
      const { size } = fs.statSync(logo);
      const { width, height } = sizeOf(logo);
      return {
        logo,
        size,
        filesize: filesize(size),
        width,
        height
      };
    })
    .filter(logo => logo.size > maxSize)
    .sort((a, b) => b.size - a.size);

  console.log(
    "LOGO | WIDTH | HEIGHT | SIZE | &nbsp;\n:-----|------:|-------:|-----:|-----"
  );
  for (const { logo, width, height, size, filesize } of logos) {
    console.log(
      [logo, width, height, filesize, danger(size / 1024 / 10)].join(" | ")
    );
  }
}

function danger(level = 0, icon = ":warning:") {
  return icon.repeat(level);
}
```

**Comment by groovecoder** [comment]
We need to add a new logo too. Should we merge this at the same time?

**Comment by groovecoder** [comment]
Is this good to merge?

**Comment by maxxcrawford** [comment]
@groovecoder Ready!

**Pull request merged**
