### PR TITLE
Update breach detail logo legibility 

### LINKED ISSUE #1037: A few difficult to see logos on a light background
While trying to verify #1021 on https://fx-breach-alerts.herokuapp.com/breaches, I noticed a few other logos that were very difficult to see on the /breaches page and their respective /breach-details/$breachName pages:

- https://fx-breach-alerts.herokuapp.com/breach-details/2fast4u
- https://fx-breach-alerts.herokuapp.com/breach-details/8tracks
- https://fx-breach-alerts.herokuapp.com/breach-details/BitcoinTalk
- https://fx-breach-alerts.herokuapp.com/breach-details/Coachella
- https://fx-breach-alerts.herokuapp.com/breach-details/DaniWeb
- https://fx-breach-alerts.herokuapp.com/breach-details/Flashback
- https://fx-breach-alerts.herokuapp.com/breach-details/FlashFlashRevolution
- https://fx-breach-alerts.herokuapp.com/breach-details/Fling
- https://fx-breach-alerts.herokuapp.com/breach-details/FreedomHostingII
- https://fx-breach-alerts.herokuapp.com/breach-details/HackingTeam
- https://fx-breach-alerts.herokuapp.com/breach-details/Kimsufi
- https://fx-breach-alerts.herokuapp.com/breach-details/LightsHope
- https://fx-breach-alerts.herokuapp.com/breach-details/LittleMonsters
- https://fx-breach-alerts.herokuapp.com/breach-details/LoungeBoard
- https://fx-breach-alerts.herokuapp.com/breach-details/Mate1
- https://fx-breach-alerts.herokuapp.com/breach-details/MyFHA
- https://fx-breach-alerts.herokuapp.com/breach-details/NaughtyAmerica
- https://fx-breach-alerts.herokuapp.com/breach-details/Nulled
- https://fx-breach-alerts.herokuapp.com/breach-details/OpenCSGO
- https://fx-breach-alerts.herokuapp.com/breach-details/ProgrammingForums
- https://fx-breach-alerts.herokuapp.com/breach-details/RetinaX
- https://fx-breach-alerts.herokuapp.com/breach-details/RosebuttBoard
- https://fx-breach-alerts.herokuapp.com/breach-details/SkTorrent
- https://fx-breach-alerts.herokuapp.com/breach-details/Soundwave
- https://fx-breach-alerts.herokuapp.com/breach-details/SprashivaiRu
- https://fx-breach-alerts.herokuapp.com/breach-details/TheFappening
- https://fx-breach-alerts.herokuapp.com/breach-details/TheFlyOnTheWall
- https://fx-breach-alerts.herokuapp.com/breach-details/TheTVDB
- https://fx-breach-alerts.herokuapp.com/breach-details/Verified
- https://fx-breach-alerts.herokuapp.com/breach-details/VictoryPhones
- https://fx-breach-alerts.herokuapp.com/breach-details/Wishbone
- https://fx-breach-alerts.herokuapp.com/breach-details/WPSandbox

---

Firefox_Monitor
**Figure 1:** Breach card

---

Firefox_Monitor
**Figure 2:** Breach details

---

Firefox_Monitor
**Figure 3:** Breach details (selected text/image)

### PR DESCRIPTION
**Pull request by maxxcrawford**
Fixes #1037 

_Note – ~Strike through~ means the logo has been updated through previous commits and does not require revisions at this time._

- ~2fast4u~
- ~8tracks~
- ~BitcoinTalk~
- ~Coachella~
- ~DaniWeb~
- ~Flashback~
- ~FlashFlashRevolution~
- [x] Fling
- [x] FreedomHostingII
- ~HackingTeam~
- [x] Kimsufi
- ~LightsHope~
- [x] LittleMonsters
- [x] LoungeBoard
- ~Mate1~
- [x] MyFHA
- [x] NaughtyAmerica
- [x] Nulled
- ~OpenCSGO~
- [x] ProgrammingForums
- ~RetinaX~
- [x] RosebuttBoard
- [x] SkTorrent
- ~Soundwave~
- ~SprashivaiRu~
- [x] TheFappening
- ~TheFlyOnTheWall~
- ~TheTVDB~
- [x] Verified
- [x] VictoryPhones
- ~Wishbone~
- ~WPSandbox~

### CODE REVIEW

**Comment by maxxcrawford** [comment]
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by pdehaan** [comment]
In fact, here's my silly script that dumps out logo dimensions+filesizes:

<details>
<summary><kbd>node ./lint-logo-size.js</kbd></summary>

```js
const fs = require("fs");

const glob = require("glob");
const filesize = require("filesize");
const sizeOf = require("image-size");

main();

async function main() {
  const logos = glob.sync("./public/img/logos/*.png");
  console.log("LOGO | WIDTH | HEIGHT | SIZE\n-----|-------|--------|------");
  for (const logo of logos) {
    const {size} = fs.statSync(logo);
    const {width, height} = sizeOf(logo);
    if (size > 10 * 1024)
      console.log([logo, width, height, filesize(size)].join(" | "));
  }
}

```
</details>

LOGO | WIDTH | HEIGHT | SIZE
-----|-------|--------|------
./public/img/logos/ArmyForceOnline.png | 560 | 75 | 19.27 KB
./public/img/logos/CannabisForum.png | 500 | 272 | 12.19 KB
./public/img/logos/COMELEC.png | 182 | 182 | 18.46 KB
./public/img/logos/CrackCommunity.png | 294 | 164 | 16.36 KB
./public/img/logos/CrossFire.png | 727 | 114 | 15.7 KB
./public/img/logos/DDO.png | 225 | 91 | 13.44 KB
./public/img/logos/Edmodo.png | 1010 | 1093 | 16.2 KB
./public/img/logos/EpicGames.png | 400 | 457 | 10.78 KB
./public/img/logos/FoxyBingo.png | 298 | 113 | 10.07 KB
./public/img/logos/LinuxMint.png | 500 | 375 | 14.28 KB
./public/img/logos/LizardSquad.png | 359 | 359 | 54.04 KB
./public/img/logos/LOTR.png | 244 | 115 | 17.17 KB
./public/img/logos/MangaTraders.png | 400 | 92 | 10.9 KB
./public/img/logos/Minefield.png | 143 | 169 | 11.72 KB
./public/img/logos/Parapa.png | 412 | 412 | 39.25 KB
./public/img/logos/PixelFederation.png | 928 | 684 | 14.95 KB
./public/img/logos/Smogon.png | 451 | 507 | 21.82 KB
./public/img/logos/Warmane.png | 95 | 115 | 10.18 KB

**Comment by maxxcrawford** [comment]
@lesleyjanenorton @groovecoder Is the Travis CI push failing an issue for this PR? Only image files were updated.

**Comment by pdehaan** [comment]
@maxxcrawford unrelated errors on Travis CI, #1370

**Comment by groovecoder** [comment]
Yup, the `npm audit` failure is fixed in `master` so the `pr` job succeeds even though the `push` job fails. Merging.

**Comment by pdehaan** [comment]
For [my own] future reference, I managed to write a quick little Puppeteer-based tool that will scrape all the /breach-details/** pages (based on latest /hibp/breaches data) and generate screenshots of the heading area (800x600 px).
https://github.com/pdehaan/blurts-breach-detail-puppeteer

Apologies, it is a bit tedious to navigate through all the shots, but infinitely quicker to clone the repo and flip through them all via Finder/Quicklook.
I was going to make an "uber-README" file, but I think it's about 19MB worth of screenshots, according to <kbd>du -sh</kbd>.

I could probably optimize slightly by only taking a screenshot of the top `<main>` element instead of the whole "above the fold", if there is interest.

**Pull request merged**
