### PR TITLE
MNTOR-1437 Instrument CTAs in authenticated pages for GA

### PR DESCRIPTION
**Pull request by rhelmer**
# References: 
Jira: MNTOR-1437

### CODE REVIEW

**Comment by rhelmer** [comment]
> This should work for these locations, but it won't work if a button or link is added after page load - might be worth adding a Mutation Observer to add/remove event listeners as well? But also fine with considering that out of scope for this.

Oh that's a good idea... this is for the guest pages which I know are all static, but I'll file a followup to do this, it feels more future-proof.

**Comment by rhelmer** [comment]
> > This should work for these locations, but it won't work if a button or link is added after page load - might be worth adding a Mutation Observer to add/remove event listeners as well? But also fine with considering that out of scope for this.
> 
> Oh that's a good idea... this is for the guest pages which I know are all static, but I'll file a followup to do this, it feels more future-proof.

https://mozilla-hub.atlassian.net/browse/MNTOR-1478

**Review by toufali — COMMENTED** [review]
Thanks @rhelmer!  A few thoughts:

- This PR's title was confusing compared to the code changes, is it intended to be _non-auth pages_?

- I see this code added to the guest layout, but a trigger is included in `breaches.js` which uses the auth'd `main.js` layout, and I don't see the code added there?  Was the intent to add the trigger to `all-breaches.js` instead, which uses the non-auth guest layout?  Otherwise, do we need to add the event listeners via main layout as well?

- The event listeners seem tucked away and could potentially be added to many elements.  A couple thoughts might be to use [event delegation](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_delegation).  Also, there's enough GA code now between both guest and main layouts that it might be worth combining these into a `ga.js` module or similar?

**Comment by rhelmer** [comment]
> 



> Thanks @rhelmer! A few thoughts:
> 
>     * This PR's title was confusing compared to the code changes, is it intended to be _non-auth pages_?
> 
>     * I see this code added to the guest layout, but a trigger is included in `breaches.js` which uses the auth'd `main.js` layout, and I don't see the code added there?  Was the intent to add the trigger to `all-breaches.js` instead, which uses the non-auth guest layout?  Otherwise, do we need to add the event listeners via main layout as well?

Yes the intent was for `all-breaches` thanks.

> 
>     * The event listeners seem tucked away and could potentially be added to many elements.  A couple thoughts might be to use [event delegation](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_delegation).  Also, there's enough GA code now between both guest and main layouts that it might be worth combining these into a `ga.js` module or similar?

Hm well it's using a query selector that should only select if the `[data-cta-id]` data attribute is set, do you think this is likely to matter? Happy to change it if so

**Pull request merged**
