### PR TITLE
Add linter for reference strings

### PR DESCRIPTION
**Pull request by flodolo**
Not sure if this should be done against localization, or another branch.

P.S. this also checks for an empty line at the end of the files

### CODE REVIEW

**Comment by flodolo** [comment]
This has a tone of noise because of trailing whitespaces, the actual changes are only around group comments :-( 

I think it's worth fixing that once and for all, but let me know if you want me to limit the changes.

**Comment by toufali** [comment]
This is great, thanks!  I think we should merge into `main`.  
Questions:
- we already have l10n linting set up on CircleCI -- is that obsolete and removable?
https://github.com/mozilla/blurts-server/blob/bd63d53b948f9efa1f78de178c6b4284d80168c7/.circleci/config.yml#L43-L52
- I assume this is using Github actions? (I'm not yet familiar)  We may be migrating our testing from CircleCI to GHA in the next couple weeks tagging @mozrokafor for visibility.

**Comment by flodolo** [comment]
> This is great, thanks! I think we should merge into `main`. Questions:
> 
>     * we already have l10n linting set up on CircleCI -- is that obsolete and removable?
>       https://github.com/mozilla/blurts-server/blob/bd63d53b948f9efa1f78de178c6b4284d80168c7/.circleci/config.yml#L43-L52

This runs a different type of checks on all locales locales (via compare-locales). It would basically flag syntax errors.

The code in this PR makes sure there are no issue with the content of the English file, and they're controls not available in compare-locales (e.g. typography).

>     * I assume this is using Github actions? (I'm not yet familiar)  We may be migrating our testing from CircleCI to GHA in the next couple weeks tagging @mozrokafor for visibility.

Correct. I saw that the kanary branch already uses GitHub action.

I'm not sure creating a PR against `main` is going to make things easier, because the FTL files diverge, and then this needs to be merged back into `localization`.

**Comment by flodolo** [comment]
> I'm not sure creating a PR against `main` is going to make things easier, because the FTL files diverge, and then this needs to be merged back into `localization`.

Correction: the en-US file is pretty similar, but there are a ton of other changes because of localization commits.

**Comment by toufali** [comment]
>I'm not sure creating a PR against main is going to make things easier, because the FTL files diverge, and then this needs to be merged back into localization.

@flodolo sorry, not following yet – As I understand there are currently two paths to `localization`:

1. a direct pull request to initiate translations, or 
2. merging `main` into `localization` for a sync of the latest build

Then, in order to get the latest translations, `localization` is merged into `main` periodically.  

It's possible that it doesn't matter which branch we merge this into, because the two will be sync'd eventually?

**Review by toufali — APPROVED** [review]

**Comment by toufali** [comment]
@flodolo further to my prev comment, I _do_ agree that since this branch is based off of `localization` we should merge there as well.  Then, when we eventually merge `localization` into `main`, all the translation commits will show up as expected.

Also, FYI the broken integration test has been fixed with the latest `main` codebase.

**Comment by flodolo** [comment]
> It's possible that it doesn't matter which branch we merge this into, because the two will be sync'd eventually?

Correct, the automation will be synced at some point when you merge the two branches.

> @flodolo further to my prev comment, I _do_ agree that since this branch is based off of `localization` we should merge there as well. Then, when we eventually merge `localization` into `main`, all the translation commits will show up as expected.

So, should we merge this now to localization, and then it will be merged to `main` later, or should I prepare a different PR based off `main` with my changes? The former seems easier.

**Comment by flodolo** [comment]
> So, should we merge this now to localization, and then it will be merged to `main` later, or should I prepare a different PR based off `main` with my changes? The former seems easier.

In case, I have also another branch ready if we prefer to land against main
https://github.com/mozilla/blurts-server/compare/main...linter_main?expand=1

One other reason I picked `localization` is that, at least recently, we created PRs agains `localization`, and `main` is not the default branch (`main-kanary` is, and I assume it's the one currently deployed).

**Comment by toufali** [comment]
agreed -- merging to `localization` first seems more sane.  We just deployed a new tag, including a localization sync, so now's a great time -- I'll push the button.

Thanks for this PR, will report back on its success!

**Pull request merged**
