### PR TITLE
Nimbus stage config

### PR DESCRIPTION
**Pull request by mansaj**
# References: 
Jira: MNTOR-
Figma: 

# Description

# Screenshot (if applicable)

Not applicable.

# How to test

# Checklist (Definition of Done)
- [ ] Localization strings (if needed) have been added.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] I've added or updated the relevant sections in readme and/or code comments
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

### CODE REVIEW

**Comment by rhelmer** [comment]
@mansaj change lgtm but I think we might need to change things on the probe-scraper side and possibly in Nimbus as well? Maybe environment variables in k8s for Cirrus too?

**Comment by mansaj** [comment]
> @mansaj change lgtm but I think we might need to change things on the probe-scraper side and possibly in Nimbus as well? Maybe environment variables in k8s for Cirrus too?

yea.. is this the only thing we need to change in this repo?

**Comment by rhelmer** [comment]
> > @mansaj change lgtm but I think we might need to change things on the probe-scraper side and possibly in Nimbus as well? Maybe environment variables in k8s for Cirrus too?
> 
> yea.. is this the only thing we need to change in this repo?

Yes I think so, we should just give Nimbus folks a heads-up that we think `stage` is a more appropriate name than `staging`.

**Review by rhelmer — APPROVED** [review]
@mansaj would you mind following up to make sure that this worked correctly? Maybe just mention at the next Nimbus meeting.

**Comment by rhelmer** [comment]
Let's hold off on this one until the roll-out tests are complete.

**Pull request closed without merging**
