### PR TITLE
bug 1569750: return entire FxA response to client

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
image

**Comment by groovecoder** [comment]
Oh crap, I meant to put the scope-check up in the controller. Will restore ASAP.

**Comment by rfk** [comment]
(IMHO, FxA should make this easier for you by accepting a `scope` parameter as part of the verification request, but it doesn't behave that way right now)

**Comment by pdehaan** [comment]
> but it doesn't behave that way right now

Dearest @rfk,
Do you have an upstream bug or something we can follow for this?

**Comment by rfk** [comment]
>  Do you have an upstream bug or something we can follow for this?

This was proposed a while ago in https://github.com/mozilla/fxa-oauth-server/issues/381, but it's not currently being tracked or worked on. It's probably more expedient to do the check locally here in monitor for now.

**Pull request merged**
